
== 常用编程语句




=== 位操作

==== 上调到字节对其大小

.按照对其大小对传入数值进行向上取整
[source, cpp]
----
uint32_t RoundUp(uint32_t x, uint32_t align) {
    return (x + align - 1) & ~ (align - 1);
}
----




=== 类型


==== `typecheck`

常用来在编译期间检查对应变量的类型，经常用于宏定义内部，用来弥补宏定义不能对参数类型进行检查的补充。

宏定义本身没有做任何更改操作，知识将type类型的变量赋值给一个临时定义出来从x取出类型的变量，如果两个类型不同则编译器会直接报错，因为不同类型之间不能进行比较。

[source, cpp]
.typecheck
----
/*
 * Check at compile time that something is of a particular type.
 * Always evaluates to 1 so you may use it easily in comparisons.
 */
#define typecheck(type,x) \
({	type __dummy; \
	typeof(x) __dummy2; \
	(void)(&__dummy == &__dummy2); \
	1; \
})
----

==== `typecheck_fn`

和typecheck类似，利用编译器对不同类型之间不能进行比较的特性对函数类型进行检查，这样实现了宏中来检查类型是否一致的作用。

.typecheck_fn
[source, cpp]
----
/*
 * Check at compile time that 'function' is a certain type, or is a pointer
 * to that type (needs to use typedef for the function type.)
 */
#define typecheck_fn(type,function) \
({	typeof(type) __tmp = function; \
	(void)__tmp; \
})
----


==== 获取结构体内部对象大小

使用宏定义实现获取结构体内存成员大小

[source, cpp]
.size_of_attribute
----
typedef struct {
  uint32_t id;
} Row;

#define size_of_attribute(Struct, Attribute) sizeof(((Struct*)0)->Attribute)

const uint32_t ID_SIZE = size_of_attribute(Row, id);
----





=== 编译器优化

==== `memory`

Memory描述符告知GCC：

1. 不要将该段内嵌汇编指令与前面的指令重新排序；也就是在执行内嵌汇编代码之前，它前面的指令都执行完毕 +
2. 不要将变量缓存到寄存器，因为这段代码可能会用到内存变量，而这些内存变量会以不可预知的方式发生改变，因此GCC插入必要的代码先将缓存到寄存器的变量值写回内存，如果后面又访问这些变量，需要重新访问内存。

如果汇编指令修改了内存，但是GCC 本身却察觉不到，因为在输出部分没有描述，此时就需要在修改描述部分增加"memory"，告诉GCC 内存已经被修改，GCC 得知这个信息后，就会在这段指令之前，插入必要的指令将前面因为优化Cache到寄存器中的变量值先写回内存，如果以后又要使用这些变量再重新读取。 其实就相当于在这里增加了一层内存屏障。

使用"volatile"也可以达到这个目的，但是我们需要在每个变量前增加该关键字，不如使用"memory"方便

经常按照如下方式使用该内联汇编，使用do-while能有效限制 `memory` 的作用范围
[source, cpp]
----
/* Optimization barrier */
/* The "volatile" is due to gcc bugs */
#define barrier() __asm__ __volatile__("": : :"memory")

#define __rcu_assign_pointer(p, v, space) \
	do { \
		barrier(); \
		(p) = (typeof(*v) __force space *)(v); \
	} while (0)
----




=== 重载

当一个类多处使用，想要直接打印，但是有不能到处对打印的地方进行重载，可以考虑逆向思考，直接重载ostream。这样一来就可以在任何地方使用cout直接打印类对象

[source, cpp]
----
struct Vector2 {
    int x;
    int y;
};

std::ostream& operator<<(std::ostream& stream, const Vector2& vector) {
    stream << vector.x << ", " << vector.y;
    return stream;
}

Vector2 vector{1,2};
std::cout << vector << std::endl;
----




