
:toc:

:icons: font

// 保证所有的目录层级都可以正常显示图片
:path: C++知识点总结/
:imagesdir: ../image/
:srcdir: ../src


// 只有book调用的时候才会走到这里
ifdef::rootpath[]
:imagesdir: {rootpath}{path}{imagesdir}
:srcdir: {rootpath}../src/
endif::rootpath[]

ifndef::rootpath[]
:rootpath: ../
:srcdir: {rootpath}{path}../src/
endif::rootpath[]

== C++常见问题


=== class、struct


==== struct

当有一个结构体定义时，如果结构体成员变量都没有进行初始化，则可以按照一般结构体进行调用，默认情况下编译器会给结构体生成各种类型的构造函数。
但是当给结构体成员初始化之后，系统会根据需要生成一个结构体成员的构造函数，必须按照这个生成的构造函数进行调用否则会失败

[source, cpp]
.IPCCfg
----
struct IPCCfg {
    std::string uuid;
    void *lpCallBack{nullptr};
    void *lpUser{nullptr};
};
----

如上面的结构体，当结构体成员别初始化列表初始化之后，编译器就会默认生成如下三个构造函数，任何不符合构造函数调用的方式进行初始化结构体都会报错，如果只是想当成简单的结构体使用那就不要对结构体成员使用初始化列表进行初始化。
[source, cpp]
----
IPCCfg::IPCCfg();
IPCCfg::IPCCfg(const IPCCfg&);
IPCCfg::IPCCfg(IPCCfg&&);
----





=== std::string底层实现COW



https://www.ccppcoding.com/archives/1201[COW]



=== 为什么不推荐使用C++的参数默认值特别是继承类中使用

在C++中，函数参数的默认值是在编译时处理的，具体来说，是在预处理阶段处理的。预处理器会在编译之前读取代码，并处理其中的预处理指令，如#include、#define等。在这个过程中，预处理器会检查函数定义的参数列表和参数的默认值，并将它们添加到函数原型中。

因此、在预处理如果用的是基类指针指向的函数，那么C++预处理器会将默认值填写成基类的默认值，如果是继承类对象调用又会使用继承类的默认值。如果基类被继承时有不同的默认值，那么你用同一个对象不同指针类型调用同一个函数时，默认值是不同的。

[source, cpp]
----

class A {
public:
    virtual int32_t GetDatabase(int name = 1, int32_t data = 10) = 0;
};

class B : public A {
public:
    int32_t GetDatabase(int name = 1,  int32_t data = 9) override {
        return data;
    }
};


B b;
A* lpa = &b;
// 结果 10
std::cout << lpa->GetDatabase() << std::endl;
// 结果 9
std::cout << b.GetDatabase() << std::endl;

}

----


=== 重载(overload)与重写(override)，overwrite的介绍
- overload（重载），即函数重载：
①在同一个类中；
②函数名字相同；
③函数参数不同（类型不同、数量不同，两者满足其一即可）；
④不以返回值类型不同作为函数重载的条件。
- override（覆盖，子类改写父类的虚函数），用于实现C++中多态：
①分别位于父类和子类中；
②子类改写父类中的virtual方法；
③与父类中的函数原型相同。
- overwrite（重写或叫隐藏，子类改写父类的非虚函数，从而屏蔽父类函数）：
①与overload类似，但是范围不同，是子类改写父类；
②与override类似，但是父类中的方法不是虚函数。

函数名相同参数不同是进行函数重载，操作符也是重载，子类对virtual的父类函数进行重写，叫覆盖(override)或者叫重写。

重载并不只是对操作符进行简单的重载操作，还有部分的隐含规则。比如对->进行重载，如果返回的是指针那么肯定不能连续调用两次->而只调用一次，重载的operator->返回的指针类型应该与原始对象类型兼容。

[source, cpp]
----
// 对应的调用方式  data.operator->().data();
std::string operator->() {
    return name;
}
// 对应的调用方式data->data()，而且需要注意的是，重载之后调用->返回的事string*解引用之后的值，也就是说，返回类型是*但是经过->的调用返回的实际是std::string类型的数据，会自动解引用
std::string* operator->() {
    return &name;
}
// 如果是普通函数，那么返回类型为std::string*调用之后，类型还是std::string不会解引用
// 调用方式data.GetName()->data();
std::string* GetName() {
    return &name;
}
----


=== 内存溢出

==== 内存溢出导致core文件调用堆栈出现问题

C++不是类型安全的，因此如果想让程序跳转到指定地址，只需要将对应的地址转换为函数指针类型，然后进行调用即可。当内存移出原先的函数标识符指向其他地址时就会导致core文件中的堆栈是乱调用的，说明内存溢出刚好导致调用函数指向的地址被修改了。







