
:toc:

:icons: font

// 保证所有的目录层级都可以正常显示图片
:path: C++知识点总结/
:imagesdir: ../image/
:srcdir: ../src


// 只有book调用的时候才会走到这里
ifdef::rootpath[]
:imagesdir: {rootpath}{path}{imagesdir}
:srcdir: {rootpath}../src/
endif::rootpath[]

ifndef::rootpath[]
:rootpath: ../
:srcdir: {rootpath}{path}../src/
endif::rootpath[]

== 模板编程






=== typename

*typename的含义*

typename本身是模板的含义，既然是模板，那么就有很多种类，有很多种类就牵涉到种类的推断，那么当需要编译器进行类型推断的时候就需要使用typename，比如下面类型推断过程 `typename U::type == typename X::type == float`，通过指定typename U::type就是告诉编译器向U类型里面推断一下U::type，那么只要指定的U类型里面有type类型，那么编译器就会把type替换成对应的类型float

[source, cpp]
----
struct X {
    typedef float type;
};

struct Y {
    typedef float type2;
};

template <typename T, typename U>
void foo(T t, typename U::type u) {
    // ...
}

void callFoo() {
    foo<int, X>(5, 5.0); // T == int, typename U::type == X::type == float
    foo<int, Y>(5, 5.0); // ???
}
----

模版的推导只是进行参数的推导，不会进行返回值的推导，因此到模版类型为函数返回值时需要使用内嵌类型来帮助模板推导内嵌类型

[source, cpp]
----
template <class T>
struct MyIter {
    typedef T value_type;  // 内嵌型别声明(netsted type)
    T* ptr; //
    explicit MyIter(T* p = 0) : ptr (p) {}
    T& operator*() const { return *ptr;}
    // ...
};
----

当一个类型是模板时，必须加上typename让编译器知道当前的类型是个模板，并不是普通的类型
.template
[source, cpp]
----
template <class I>
typename I::value_type   // 这里是函数的返回值
func (I ite)
{
    return ite;
}
----


=== 偏特化(Partial Specialization)

偏特化的大致意思如果一个class template拥有一个以上的template参数，我们可以针对某个或者全部的template参数进行特化工作。

[source, cpp]
----
template <typename U, typename V, typename T>
class C {...};
----

partial的字面意思容易误导人，让人们以为所谓的偏特化一定是将其中的U,V,T指定为特定的某个参数值。其实不然，所谓的Partial Specialization意思是提供一份template定义式，而其本身仍为templatized。《泛型思维》中的定义更加准确一点：针对任何template参数更进一步的条件限制所设计出来的一个特化版本。

[source, cpp]
----
template<typename T>
class C{...};    // 这个泛化版本允许接收T为任何型别

/*******************************/
template<typename T>
class C<T*> {...}; // 这个特化版本仅适用于T为指针的情况，
                    // T为原生指针，也是对T为任何型别的一个更进一步的条件限制

----


=== traits(萃取)

使用T*可以对模板进行偏特化，但是一般定义模板只会定义T类型的，因此内嵌型别也只会在T类型中声明，这个时候就得借助萃取技术来实现内置类型的获取了。

.traits
[source, cpp]
----

template <class T>
struct MyIter {
    typedef T value_type;  // 内嵌型别声明(netsted type)
    T* ptr; //
    explicit MyIter(T* p = 0) : ptr (p) {}
    T& operator*() const { return *ptr;}
    // ...
};

template <class I>
typename I::value_type   // 这里是函数的返回值
func (I ite)
{
    return ite;
}

----

将上述代码使用萃取技术

[source, cpp]
----
template <class I>
struct iterator_traits {   // traits 意为特性
    typedef typename I::value_type value_type;
}

template <class I>
typename iterator_traits<T>::value_type   // 这里是函数的返回值
func (I ite)
{
    return ite;
}
----

经过traits的封装之后，带来的好处就是特化版本也能进行处理了

[source, cpp]
----
template <class I>
struct iterator_traits<I*> {   // traits 意为特性
    typedef I value_type;
}
----

而且经过上述处理之后，原生指针本身是没有value_type的也能使用value_type了


=== 函数绑定(mem_fn)

使用mem_fn轻松将成员函数绑定为可以直接调用的函数形式。

[source, cpp]
----
#include <iostream>
#include <functional>

class MyClass {
public:
    void print(int value) const {
        std::cout << "Value: " << value << std::endl;
    }
};

int main() {
    MyClass myObject;
    //auto boundPrint = std::bind(std::mem_fn(&MyClass::print), &myObject, std::placeholders::_1);
    //std::function<void(int)> boundPrint = std::bind(std::mem_fn(&MyClass::print), &myObject, std::placeholders::_1);
    std::function<void(int)> boundPrint = std::bind(&MyClass::print, &myObject, std::placeholders::_1);
    boundPrint(10);  // 输出 "Value: 10"
    return 0;
}
----




=== 参考

https://gcc.gnu.org/onlinedocs/gcc-4.6.0/libstdc++/api/dir_e96818ea44b74decf0d0168e5ad4fe6f.html[stl gcc各个版本在线手册]








