

:toc:

// 保证所有的目录层级都可以正常显示图片
:path: utils/
:imagesdir: ../image/
:srcdir: ../src
:datadir: data/

// 只有book调用的时候才会走到这里
ifdef::rootpath[]
:imagesdir: {rootpath}{path}{imagesdir}

:srcdir: {rootpath}../src/
:datadir: {rootpath}{path}../data/
endif::rootpath[]

ifndef::rootpath[]
:rootpath: ../

:srcdir: {rootpath}{path}../src/
:datadir: {rootpath}{path}/data/
endif::rootpath[]











https://makefiletutorial.com/#makefile-cookbook[Makefile cookbook]