
:toc:

:icons: font

// 保证所有的目录层级都可以正常显示图片
:path: 数据库/
:imagesdir: ../image/
:srcdir: ../src


// 只有book调用的时候才会走到这里
ifdef::rootpath[]
:imagesdir: {rootpath}{path}{imagesdir}
:srcdir: {rootpath}../src/
endif::rootpath[]

ifndef::rootpath[]
:rootpath: ../
:srcdir: {rootpath}{path}../src/
endif::rootpath[]


== 数据库教程

https://github.com/zzu-andrew/note_book[仓库地址]

- 存储数据的格式是怎样的(在内存和磁盘上)
- 什么时候存储的数据会从内存转移到磁盘上
- 为什么数据库中一个table中只能有一个主键
- 事务操作中回滚是如何实现的？
- 索引的格式是什么
- 全表扫描什么时候以及如何完成的
- 预声明语句是按照什么格式存储的？

总之一句话，数据库是如何工作的？

=== 简单的REPL(read-execute-print loop)
==== Sqlite

这个教程就是对sqlite的模仿，所以有必要先了解一下sqlite的组成，sqlite分为前端部分和后端部分。

前端部分主要完成一些列组件检索或修改数据，主要如下：

- tokenizer
- parser
- code generator

前端接收的是sql语句，输出的是sqlite虚拟机字节码，后端组成如下：

- virtual machine
- B-tree
- pager
- os interface

==== 一个简单的REPL
当你使用命令行启动sqlite时，sqlite会开始一个read-execute-print loop
[source, SQL]
----
[xxx@localhost]$sqlite3
sqlite> create table users (id int, username varchar(255), email varchar(255));
sqlite> .tables
users
sqlite> .exit
----
为了实现和sqlite同样的效果，我们需要实现一个循环，在循环里面打印提示，并且持续接收输入然后处理输入

[source, c]
.dm_main process input
----
int main(int argc, char* argv[]) {
    InputBuffer* input_buffer = new_input_buffer();
    while (true) {
        print_prompt();
        read_input(input_buffer);

        if (strcmp(input_buffer->buffer, ".exit") == 0) {
            close_input_buffer(input_buffer);
            exit(EXIT_SUCCESS);
        } else {
            printf("Unrecognized command '%s'.\n", input_buffer->buffer);
        }
    }
}
----

在这里定义一个 `InputBuffer` 用来封装getline获取的内容

[source, cpp]
----
typedef struct {
  char* buffer;
  size_t buffer_length;
  ssize_t input_length;
} InputBuffer;

InputBuffer* new_input_buffer() {
  InputBuffer* input_buffer = (InputBuffer*)malloc(sizeof(InputBuffer));
  input_buffer->buffer = NULL;
  input_buffer->buffer_length = 0;
  input_buffer->input_length = 0;

  return input_buffer;
}
----

接下来，定义一个print_prompt来给用户打印提示，每次调用读取之前我们都会调用一下这个函数

[source, cpp]
----
void print_prompt() { printf("db > "); }
----

使用getline读取用户的输入，但是这里需要注意的是getline官方给出的说明：
也就是说，当传入的是一个地址指向的内容是nullptr的时候，getline会默认申请一段内存，在使用结束的时候需要用户自行进行释放。否则或存在内存泄露，当然如果有必要用户可以自己根据需要自行申请内存，只要传入的指针地址不是nullptr那么getline就不会在申请内存

If *lineptr is NULL, then getline() will allocate a buffer for storing the line, which should be freed by the user program.   (In  this  case,
the value in *n is ignored.)

因此需要定义一个配套的内存释放函数
[source, cpp]
----
ssize_t getline(char **lineptr, size_t *n, FILE *stream);

void read_input(InputBuffer* input_buffer) {
  ssize_t bytes_read =
      getline(&(input_buffer->buffer), &(input_buffer->buffer_length), stdin);

  if (bytes_read <= 0) {
    printf("Error reading input\n");
    exit(EXIT_FAILURE);
  }

  // Ignore trailing newline
  input_buffer->input_length = bytes_read - 1;
  input_buffer->buffer[bytes_read - 1] = 0;
}

// 配套内存释放函数
void close_input_buffer(InputBuffer* input_buffer) {
    free(input_buffer->buffer);
    free(input_buffer);
}
----

最后我们只需要在循环中挨个执行输入的指令即可，全部代码如下：

[source, cpp]
----

#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct {
    char* buffer;
    size_t buffer_length;
    ssize_t input_length;
} InputBuffer;

InputBuffer* new_input_buffer() {
    InputBuffer* input_buffer = (InputBuffer*)malloc(sizeof(InputBuffer));
    input_buffer->buffer = NULL;
    input_buffer->buffer_length = 0;
    input_buffer->input_length = 0;

    return input_buffer;
}

void print_prompt() { printf("db > "); }

void read_input(InputBuffer* input_buffer) {
    //If *lineptr is NULL, then getline() will allocate a buffer for storing the line, which should be freed by the user program
    ssize_t bytes_read =
            getline(&(input_buffer->buffer), &(input_buffer->buffer_length), stdin);

    if (bytes_read <= 0) {
        printf("Error reading input\n");
        exit(EXIT_FAILURE);
    }

    // Ignore trailing newline
    input_buffer->input_length = bytes_read - 1;
    input_buffer->buffer[bytes_read - 1] = 0;
}

void close_input_buffer(InputBuffer* input_buffer) {
    free(input_buffer->buffer);
    free(input_buffer);
}

int main(int argc, char* argv[]) {
    InputBuffer* input_buffer = new_input_buffer();
    while (true) {
        print_prompt();
        read_input(input_buffer);

        if (strcmp(input_buffer->buffer, ".exit") == 0) {
            close_input_buffer(input_buffer);
            exit(EXIT_SUCCESS);
        } else {
            printf("Unrecognized command '%s'.\n", input_buffer->buffer);
        }
    }
}
----

执行过程如下：

因为这里只实现了.exit这个指令，所以在执行过程中也只会响应这一个指令
[source, SQL]
----
$./a.out
db > .tables
Unrecognized command '.tables'.
db > .exit
----

=== 世界上最简单的SQL编译器和虚拟机

这里目的是模仿sqlite，那sqlite的前端实现了SQL的编译-解析字符串并且输出内部展现形式-字节码
这些字节码会传输给虚拟机，虚拟机会执行这些字节码，具体的可以参考sqlite架构： https://www.sqlite.org/arch.html[sqlite arch]

将整个数据操作过程分隔成两个部分有两个好处：

- 减少每个部分的复杂度
- 允许将编译的字节码缓存以提高性能

为了实现这些我们可以对main进行如下改造

[source, cpp]
----
// 这里先把 .开头的meta指令单独拎出来执行
if (input_buffer->buffer[0] == '.') {
    switch (do_meta_command(input_buffer)) {
        case (META_COMMAND_SUCCESS):
            continue;
        case (META_COMMAND_UNRECOGNIZED_COMMAND):
            printf("Unrecognized command '%s'\n", input_buffer->buffer);
            continue;
    }
}

// sqlite声明语句
Statement statement;
switch (prepare_statement(input_buffer, &statement)) {
    case (PREPARE_SUCCESS):
        break;
    case (PREPARE_UNRECOGNIZED_STATEMENT):
        printf("Unrecognized keyword at start of '%s'.\n",
                 input_buffer->buffer);
    continue;
}

execute_statement(&statement);
printf("Executed.\n");
----


像.exit这样的Non-SQL声明我们称之为 `meta-command`，这些指令的特点就是所有指令都是使用.开头，因此我们可以根据是否.开头来将这些指令和正常的SQL指令进行区分处理。

> meta-元，是抽象的抽象，就像模板一样被称为元编程，编程本身就是对具体事务的抽象，模板是对抽象代码的进一步抽象，因此称模板编程为元编程。

接下来我们添加一个步骤将输入行转换为语句的内部表示形式，这是一个粗糙的sqlite前端

最后我们将上述前端处理之后的声明放入execute_statement，这个函数将会最终用来实现虚拟机的功能

do_meta_command接口只是对现有函数的一些简单封装，并且预留足够的空间方便添加更多的指令

[source, cpp]
.do_meta_command example
----
MetaCommandResult do_meta_command(InputBuffer* input_buffer) {
  if (strcmp(input_buffer->buffer, ".exit") == 0) {
    exit(EXIT_SUCCESS);
  } else {
    return META_COMMAND_UNRECOGNIZED_COMMAND;
  }
}
----

目前预声明语句只包含了两种可能的值，后期会进行扩展
[source, cpp]
----
typedef enum { STATEMENT_INSERT, STATEMENT_SELECT } StatementType;

typedef struct {
  StatementType type;
} Statement;
----

添加prepare_statement(SQL compiler)，但是目前只能处理两个指令

[source, cpp]
----
PrepareResult prepare_statement(InputBuffer* input_buffer,
                                Statement* statement) {
  if (strncmp(input_buffer->buffer, "insert", 6) == 0) {
    statement->type = STATEMENT_INSERT;
    return PREPARE_SUCCESS;
  }
  if (strcmp(input_buffer->buffer, "select") == 0) {
    statement->type = STATEMENT_SELECT;
    return PREPARE_SUCCESS;
  }

  return PREPARE_UNRECOGNIZED_STATEMENT;
}
----

最后让我们来实现执行的步骤

[source, cpp]
----
void execute_statement(Statement* statement) {
  switch (statement->type) {
    case (STATEMENT_INSERT):
      printf("This is where we would do an insert.\n");
      break;
    case (STATEMENT_SELECT):
      printf("This is where we would do a select.\n");
      break;
  }
}
----

这里实现知识搭建一些框架而已，真正的功能还没有实现，因此没有任何的错误处理等功能，具体的执行效果如下：

[source, SQL]
----
$./a.out
db > insert foo bar
This is where we would do an insert.
Executed.
db > delete foo
Unrecognized keyword at start of 'delete foo'.
db > select
This is where we would do a select.
Executed.
db > .tables
Unrecognized command '.tables'
db > .exit
----

现在数据库代码正在组件成型，如果能存储一些数据是不是就更加好了？在下一章节中我们将会实现insert和select，创造出一个最为糟糕的数据库存储实现，下面是代码diff的提交实现记录

代码仓库见文章开头：
commitId : 21327325bbc2d63a12e4c1bdd3ed0a3f5bdd687d

=== 在内存中，仅支持追加的单表数据库

为了简化数据库的实现，需要对数据库添加一些限制

- 支持两个操作：插入行和打印多行数据
- 只是使用内存
- 仅支持单个硬编码表

硬编码表设计如下：

.hard code table
// 指定表为3列，并指定相对宽度
[cols="1,1", options="header"]
|===
|column
|type

|id
|integer

|username
|varchar(32)

|email
|varchar(255)

|===

这种模式看着简单但是已经能够支持多种数据类型和多种大小的数据文本了。

insert语句能像如下方式使用

[source, cpp]
----
insert 1 cstack foo@bar.com
----

需要升级prepare_statement接口才能支持这些功能，升级之后如下：

[source, cpp]
----
PrepareResult prepare_statement(InputBuffer* input_buffer,
                                Statement* statement) {
    if (strncmp(input_buffer->buffer, "insert", 6) == 0) {
        statement->type = STATEMENT_INSERT;
        int args_assigned = sscanf(
                        input_buffer->buffer, "insert %d %s %s", &(statement->row_to_insert.id),
                        statement->row_to_insert.username, statement->row_to_insert.email);
        if (args_assigned < 3) {
            return PREPARE_SYNTAX_ERROR;
        }
        return PREPARE_SUCCESS;
    }
    if (strcmp(input_buffer->buffer, "select") == 0) {
        statement->type = STATEMENT_SELECT;
        return PREPARE_SUCCESS;
    }

    return PREPARE_UNRECOGNIZED_STATEMENT;
}
----

[source, cpp]
----
typedef struct {
    uint32_t id;
    char username[COLUMN_USERNAME_SIZE];
    char email[COLUMN_EMAIL_SIZE];
} Row;


typedef struct {
    StatementType type;
    Row row_to_insert;  // only used by insert statement
} Statement;
----

在实际使用中我们需要将这些结构数据复制到一个为表的数据结构中，在SQLite中使用B-tree来实现快速查询，插入和删除，这里只是简单的使用一个类B-tree，这个类B-tree会自动按照页增长，但是实际只是将这些页按照数组的形式组织。

下面是实现计划项：

- 我们称存储多行数据的内存块为页
- 每页尽量多的存储行数据
- 行数据被序列化之后紧凑的存储在页数据中
- 页按照需求进行申请
- 保留一个变长数组存储指向页的指针

首先设计一个紧凑的行数据：

[source, cpp]
----
#define size_of_attribute(Struct, Attribute) sizeof(((Struct*)0)->Attribute)

const uint32_t ID_SIZE = size_of_attribute(Row, id);
const uint32_t USERNAME_SIZE = size_of_attribute(Row, username);
const uint32_t EMAIL_SIZE = size_of_attribute(Row, email);
const uint32_t ID_OFFSET = 0;
const uint32_t USERNAME_OFFSET = ID_OFFSET + ID_SIZE;
const uint32_t EMAIL_OFFSET = USERNAME_OFFSET + USERNAME_SIZE;
const uint32_t ROW_SIZE = ID_SIZE + USERNAME_SIZE + EMAIL_SIZE;
----

这样定义之后也就意味着序列后的行如下：

.hard code table
// 指定表为3列，并指定相对宽度
[cols="2,1,1", options="header"]
|===
|column
|size(bytes)
|offset

|id
|4
|0

|username
|32
|4

|email
|255
|36

|total
|291
|291

|===

数据放入，同样需要拿数据的时候需要将数据从内存中取出来

[soruce, cpp]
----
void serialize_row(Row* source, void* destination) {
  memcpy(destination + ID_OFFSET, &(source->id), ID_SIZE);
  memcpy(destination + USERNAME_OFFSET, &(source->username), USERNAME_SIZE);
  memcpy(destination + EMAIL_OFFSET, &(source->email), EMAIL_SIZE);
}

void deserialize_row(void* source, Row* destination) {
  memcpy(&(destination->id), source + ID_OFFSET, ID_SIZE);
  memcpy(&(destination->username), source + USERNAME_OFFSET, USERNAME_SIZE);
  memcpy(&(destination->email), source + EMAIL_OFFSET, EMAIL_SIZE);
}
----

接下来定义一个table用来存放所有的页数据

[source, cpp]
----
const uint32_t PAGE_SIZE = 4096;
#define TABLE_MAX_PAGES 100
const uint32_t ROWS_PER_PAGE = PAGE_SIZE / ROW_SIZE;
const uint32_t TABLE_MAX_ROWS = ROWS_PER_PAGE * TABLE_MAX_PAGES;

typedef struct {
  uint32_t num_rows;
  void* pages[TABLE_MAX_PAGES];
} Table;
----

这里将页大小定义成4K大小，因为大多数机器的虚拟内存也是定义为4K，也就以为着数据库中使用的页和实际中机器中的页大小是相等的，这样就能保证操作系统会对数据库中
的页进行整体而不是分隔来进行操作。

将页的个数定义为100，因为这里使用的是内存，当将这些数据转移到树结构的时候，页的个数将会只有文件大小一个限制

行数据不要在不同的页中，这样就能保证读写数据非常的简单

[source, cpp]
----
void* row_slot(Table* table, uint32_t row_num) {
  uint32_t page_num = row_num / ROWS_PER_PAGE;
  void* page = table->pages[page_num];
  if (page == NULL) {
    // Allocate memory only when we try to access page
    page = table->pages[page_num] = malloc(PAGE_SIZE);
  }
  uint32_t row_offset = row_num % ROWS_PER_PAGE;
  uint32_t byte_offset = row_offset * ROW_SIZE;
  return page + byte_offset;
}
----

经过改造之后，我们的数据库能够实现数据的插入和查找功能，具体执行结果如下：
[source, SQL]
----
$./a.out
db > insert 1 cstack foo@bar.com
Executed.
db > insert 2 bob bob@example.com
Executed.
db > select
(1, cstack, foo@bar.com)
(2, bob, bob@example.com)
Executed.
db > insert foo bar 1
Syntax error. Could not parse statement.
db > .exit
----

代码仓库见文章开头，commitID : d88dab30a3ce51c74a6558f715f8949807609b89

添加测试，commitID : ebb6923ee0d92cfc4689f776a58f5df556bbb781


































































