:toc:

// 保证所有的目录层级都可以正常显示图片
:path: go/
:imagesdir: ../image/

// 只有book调用的时候才会走到这里
ifdef::rootpath[]
:imagesdir: {rootpath}{path}{imagesdir}
endif::rootpath[]


== go语言基础


=== 1. make和new的区别
内置函数new计算类型的大小，并为其分配零值内存，返回指针

make会被编译器翻译成具体的创建函数，由其分配内存和初始化成员结构，返回对象的引用而非指针

**new**:

- new的作用是初始化一个类型的指针
- new函数是内建函数
- 使用new来进行分配空间
- 传递给new函数的是一个类型，而不是一个值
- 返回值指向这个新分配的地址的指针

[source, go]
----
package main

import "fmt"

func main() {
	p := new(Table)
	person := Table{"LittleTable"}
	fmt.Printf("%T\n",p)
	fmt.Printf("%T\n",person)

}
type Table struct {
	name string
}

// 输出结果为
// *main.Table
// main.Table

// 所以new函数返回的是指针，该指针指向Table实体

----

**make**:

- make的作用是为slice、map或chan的初始化
- make返回类型的引用而不是指针，而返回值类型依赖具体传入类型
- make函数是内健函数，函数定义：

[source, go]
----
// The make built-in function allocates and initializes an object of type
// slice, map, or chan (only). Like new, the first argument is a type, not a
// value. Unlike new, make's return type is the same as the type of its
// argument, not a pointer to it. The specification of the result depends on
// the type:
//	Slice: The size specifies the length. The capacity of the slice is
//	equal to its length. A second integer argument may be provided to
//	specify a different capacity; it must be no smaller than the
//	length. For example, make([]int, 0, 10) allocates an underlying array
//	of size 10 and returns a slice of length 0 and capacity 10 that is
//	backed by this underlying array.
//	Map: An empty map is allocated with enough space to hold the
//	specified number of elements. The size may be omitted, in which case
//	a small starting size is allocated.
//	Channel: The channel's buffer is initialized with the specified
//	buffer capacity. If zero, or the size is omitted, the channel is
//	unbuffered.
func make(t Type, size ...IntegerType) Type
----


=== Go Embed简明教程

go语言程序都是编译成二进制可执行文件的，但是实际执行时除了需要可执行程序，还需要一些静态文件，比如html模板等，于是就有人想如果Go官方能内建支持就好了。2019末一个提案被提出 [issue#35950](https://links.jianshu.com/go?to=https://github.com/golang/go/issues/35950),期望Go官方编译器支持嵌入静态文件。后来Russ Cox专门写了一个设计文档 [Go command support for embedded static assets](https://links.jianshu.com/go?to=https://go.googlesource.com/proposal/+/master/design/draft-embed.md), 并最终实现了它。

- 需要注意的这个功能在go 1.16beta之后才支持
- 对于单个的文件，支持嵌入为字符串和 byte slice
- 对于多个文件和文件夹，支持嵌入为新的文件系统FS
- 比如导入 "embed"包，即使无显式的使用

  `go:embed`指令用来嵌入，必须紧跟着嵌入后的变量名

- 只支持嵌入为string, byte slice和embed.FS三种类型，这三种类型的别名(alias)和命名类型(如type S string)都不可以

==== 嵌入为字符串

假设有一个文件test.txt文件内容为hello world

如下代码编译之后s的值就变成了"hello world"

[source,go]
----
//go:embed test.txt
var s string
----

==== 嵌入为byte slice

你还可以将文件的内容嵌入为slice of byte，也就是一个字节数组

[source,go]
----
//go:embed test.txt
var b []byte
----

==== 嵌入为fs.FS

甚至你可以嵌入为一个文件系统，这种方式在嵌入多个文件的时候非常有用

支持嵌入多个文件如：

[source,go]
----
//go:embed test.txt hello.txt
----

支持指定文件夹如：

[source,go]
----
//go:embed file/file.txt
----

支持多行方式嵌入如：

[source,go]
----
//go:embed test.txt hello.txt
//go:embed file/file.txt
//go:embed test.txt hello.txt
//go:embed file/file.txt
var f embed.FS

// 使用
// 嵌入为文件系统
data, _ :=  f.ReadFile("test.txt")
fmt.Println(string(data))
data, _ = f.ReadFile("hello.txt")
fmt.Println(string(data))
----

支持嵌入文件夹

[source]
----
//go:embed file
var d embed.FS
----

完整代码实现

[source,go]
----
package main

import (
   "embed"
   _ "embed"
   "fmt"
)

//go:embed test.txt
var s string

//go:embed test.txt
var b []byte

//go:embed test.txt hello.txt
//go:embed file/file.txt
var f embed.FS

//go:embed file
var d embed.FS

//go:embed file/*.txt
var pre embed.FS


func main() {
   // 直接嵌入
   fmt.Println(s)
   fmt.Println(b)

   // 嵌入为文件系统
   data, _ :=  f.ReadFile("test.txt")
   fmt.Println(string(data))
   data, _ = f.ReadFile("hello.txt")
   fmt.Println(string(data))
   // 嵌入的时候文件是啥，这里要对应指定为相同的文件路径
   data, _ = f.ReadFile("file/file.txt")
   fmt.Println(string(data))

   data, _ = d.ReadFile("file/file.txt")
   fmt.Println(string(data))

   data, _ = pre.ReadFile("file/name.txt")
   fmt.Println(string(data))
}
----









































































