
:toc:

:icons: font

// 保证所有的目录层级都可以正常显示图片
:path: C++知识点总结/
:imagesdir: ../image/
:srcdir: ../src


// 只有book调用的时候才会走到这里
ifdef::rootpath[]
:imagesdir: {rootpath}{path}{imagesdir}
:srcdir: {rootpath}../src/
endif::rootpath[]

ifndef::rootpath[]
:rootpath: ../
:srcdir: {rootpath}{path}../src/
endif::rootpath[]

== C++常见问题


=== class、struct


==== struct

当有一个结构体定义时，如果结构体成员变量都没有进行初始化，则可以按照一般结构体进行调用，默认情况下编译器会给结构体生成各种类型的构造函数。
但是当给结构体成员初始化之后，系统会根据需要生成一个结构体成员的构造函数，必须按照这个生成的构造函数进行调用否则会失败

[source, cpp]
.IPCCfg
----
struct IPCCfg {
    std::string uuid;
    void *lpCallBack{nullptr};
    void *lpUser{nullptr};
};
----

如上面的结构体，当结构体成员别初始化列表初始化之后，编译器就会默认生成如下三个构造函数，任何不符合构造函数调用的方式进行初始化结构体都会报错，如果只是想当成简单的结构体使用那就不要对结构体成员使用初始化列表进行初始化。
[source, cpp]
----
IPCCfg::IPCCfg();
IPCCfg::IPCCfg(const IPCCfg&);
IPCCfg::IPCCfg(IPCCfg&&);
----





=== std::string底层实现COW



https://www.ccppcoding.com/archives/1201[COW]



=== 为什么不推荐使用C++的参数默认值特别是继承类中使用

在C++中，函数参数的默认值是在编译时处理的，具体来说，是在预处理阶段处理的。预处理器会在编译之前读取代码，并处理其中的预处理指令，如#include、#define等。在这个过程中，预处理器会检查函数定义的参数列表和参数的默认值，并将它们添加到函数原型中。

因此、在预处理如果用的是基类指针指向的函数，那么C++预处理器会将默认值填写成基类的默认值，如果是继承类对象调用又会使用继承类的默认值。如果基类被继承时有不同的默认值，那么你用同一个对象不同指针类型调用同一个函数时，默认值是不同的。

[source, cpp]
----

class A {
public:
    virtual int32_t GetDatabase(int name = 1, int32_t data = 10) = 0;
};

class B : public A {
public:
    int32_t GetDatabase(int name = 1,  int32_t data = 9) override {
        return data;
    }
};


B b;
A* lpa = &b;
// 结果 10
std::cout << lpa->GetDatabase() << std::endl;
// 结果 9
std::cout << b.GetDatabase() << std::endl;

}

----

